
//! Autogenerated weights for `peaq_pallet_storage`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-99-1-200-206`, CPU: `AMD EPYC 7R32`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev-local")`, DB CACHE: 1024

// Executed Command:
// ./target/release/peaq-node
// benchmark
// pallet
// --chain=dev-local
// --execution=native
// --wasm-execution=compiled
// --pallet=peaq-pallet-storage
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=weight.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `peaq_pallet_storage`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Balances::Reserves` (r:1 w:1)
	/// Proof: `Balances::Reserves` (`max_values`: None, `max_size`: Some(1249), added: 3724, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `PeaqStorage::ItemStore` (r:1 w:1)
	/// Proof: `PeaqStorage::ItemStore` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn add_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `254`
		//  Estimated: `4714`
		// Minimum execution time: 48_561_000 picoseconds.
		Weight::from_parts(49_172_000, 0)
			.saturating_add(Weight::from_parts(0, 4714))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `PeaqStorage::ItemStore` (r:1 w:1)
	/// Proof: `PeaqStorage::ItemStore` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn update_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `3771`
		// Minimum execution time: 23_701_000 picoseconds.
		Weight::from_parts(24_111_000, 0)
			.saturating_add(Weight::from_parts(0, 3771))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PeaqStorage::ItemStore` (r:1 w:0)
	/// Proof: `PeaqStorage::ItemStore` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn get_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `411`
		//  Estimated: `3771`
		// Minimum execution time: 21_911_000 picoseconds.
		Weight::from_parts(22_361_000, 0)
			.saturating_add(Weight::from_parts(0, 3771))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Balances::Reserves` (r:1 w:1)
	/// Proof: `Balances::Reserves` (`max_values`: None, `max_size`: Some(1249), added: 3724, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `PeaqStorage::ItemStore` (r:1 w:1)
	/// Proof: `PeaqStorage::ItemStore` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn remove_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `4714`
		// Minimum execution time: 50_082_000 picoseconds.
		Weight::from_parts(50_701_000, 0)
			.saturating_add(Weight::from_parts(0, 4714))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
